eureka:
  instance:
    hostname: Client_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka


spring:
  application:
    name: Client_Service

  security:
    user:
      name: mabrouka
      password: annabi
  datasource:
    url: jdbc:postgresql://postgres:5432/client_db
    username: postgres
    password: insy2s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
  
user:
  url: http://service-gateway:8090/api/keycloak/users
email:
  url: http://service-gateway:8090/api/mail/
