eureka :
  instance:
    client:
      serviceUrl:
        defaultZone: http://service-registry:8761/


spring:
  application:
    name: Client_Service

  security:
    user:
      name: mabrouka
      password: annabi
  datasource:
    url: jdbc:postgresql://posgres:5432/Client_db
    username: postgres
    password: insy2s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
  
user:
  url: http://service-keycloak-auth:8090/api/keycloak/users
email:
  url: http://service-email:8090/api/mail/
