spring:
  application:
    name: Consultant_Service
  security:
    user:
      name: mabrouka
      password: annabi


  # Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ConsultantDB
    username: postgres

    password: insy2s

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : true
    properties:
      hibernate:
        format_sql: true
#  Server configuration
server:
  port: 8085
  
consultant:
  url: http://localhost:8090/api/consultants
user:
  url: http://localhost:8090/api/keycloak/users
email:
  url: http://localhost:8090/api/mail
address:
  url: http://localhost:8090/api/address

