#urlApp: "http://localhost:5173/verify"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: insys2stunteam@gmail.com
    password: forgrhbgftvedmvu
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  application:
      name: Email_Service

eureka:
  instance:
    hostname: Email_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka




#  Server configuration
server:
      port: 8086
