urlApp: "http://localhost:5173/verify"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: insys2stunteam@gmail.com
    password: forgrhbgftvedmvu
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  application:
      name: Email_Service

eureka :
      instance:
            client:
                  serviceUrl:
                        defaultZone: http://localhost:8761/




#  Server configuration
server:
      port: 8086
