eureka :
  instance:
   client:
    serviceUrl:
     defaultZone: http://service-registry:8761/eureka

 




spring:
  application:
    name: Gateway_Service
  security:
    user:
      name: mabrouka
      password: annabi
server:
  port: 8090





