spring:
  application:
    name: Ged_Service


    
  security:
    user:
      name: mabrouka
      password: annabi
  data:
    mongodb:
      database: insy2s
      username: insy2s
      password: insy2s
      host: localhost
      port: 27017
server:
  port: 8088
#  Eureka configuration

eureka :
  instance:
    client:
      serviceUrl:
        defaultZone: http://service-registry:8761/

user:
  url: http://service-gateway:8090/api/auth
